const axios = require("axios");

// LISTA DE TERRITÓRIOS DE IDENTIDADE. PROVIDA
// AQUI POR NÃO HAVER API COM A LISTAGEM.
const listaTerritoriosIdentidade = [
  {
    territorio: "Bacia do Jacuípe",
    municipios: [
      "Baixa Grande",
      "Capela do Alto Alegre",
      "Capim Grosso",
      "Gavião",
      "Ipirá",
      "Mairi",
      "Nova Fátima",
      "Pé de Serra",
      "Pintadas",
      "Quixabeira",
      "Riachão do Jacuípe",
      "São José do Jacuípe",
      "Serra Preta",
      "Várzea da Roça",
      "Várzea do Poço",
    ],
  },
  {
    territorio: "Bacia do Paramirim",
    municipios: [
      "Boquira",
      "Botuporã",
      "Caturama",
      "Érico Cardoso",
      "Ibipitanga",
      "Macaúbas",
      "Paramirim",
      "Rio do Pires",
    ],
  },
  {
    territorio: "Bacia do Rio Corrente",
    municipios: [
      "Brejolândia",
      "Canápolis",
      "Cocos",
      "Coribe",
      "Correntina",
      "Jaborandi",
      "Santa Maria da Vitória",
      "Santana",
      "São Félix do Coribe",
      "Serra Dourada",
      "Tabocas do Brejo Velho",
    ],
  },
  {
    territorio: "Bacia do Rio Grande",
    municipios: [
      "Angical",
      "Baianópolis",
      "Barreiras",
      "Buritirama",
      "Catolândia",
      "Cotegipe",
      "Cristópolis",
      "Formosa do Rio Preto",
      "Luís Eduardo Magalhães",
      "Mansidão",
      "Riachão das Neves",
      "Santa Rita de Cássia",
      "São Desidério",
      "Wanderley",
    ],
  },
  {
    territorio: "Baixo Sul",
    municipios: [
      "Aratuípe",
      "Cairu",
      "Camamu",
      "Gandu",
      "Ibirapitanga",
      "Igrapiúna",
      "Ituberá",
      "Jaguaripe",
      "Nilo Peçanha",
      "Piraí do Norte",
      "Presidente Tancredo Neves",
      "Taperoá",
      "Teolândia",
      "Valença",
      "Wenceslau Guimarães",
    ],
  },
  {
    territorio: "Chapada Diamantina",
    municipios: [
      "Abaíra",
      "Andaraí",
      "Barra da Estiva",
      "Boninal",
      "Bonito",
      "Ibicoara",
      "Ibitiara",
      "Iramaia",
      "Iraquara",
      "Itaeté",
      "Jussiape",
      "Lençóis",
      "Marcionílio Souza",
      "Morro do Chapéu",
      "Mucugê",
      "Nova Redenção",
      "Novo Horizonte",
      "Palmeiras",
      "Piatã",
      "Rio de Contas",
      "Seabra",
      "Souto Soares",
      "Utinga",
      "Wagner",
    ],
  },
  {
    territorio: "Costa do Descobrimento",
    municipios: [
      "Belmonte",
      "Eunápolis",
      "Guaratinga",
      "Itabela",
      "Itagimirim",
      "Itapebi",
      "Porto Seguro",
      "Santa Cruz Cabrália",
    ],
  },
  {
    territorio: "Extremo Sul",
    municipios: [
      "Alcobaça",
      "América Dourada",
      "Caravelas",
      "Ibirapuã",
      "Itamaraju",
      "Itanhém",
      "Jucuruçu",
      "Lajedão",
      "Medeiros Neto",
      "Mucuri",
      "Nova Viçosa",
      "Prado",
      "Teixeira de Freitas",
      "Vereda",
    ],
  },
  {
    territorio: "Irecê",
    municipios: [
      "América Dourada",
      "Barra do Mendes",
      "Barro Alto",
      "Cafarnaum",
      "Canarana",
      "Central",
      "Gentio do Ouro",
      "Ibipeba",
      "Ibititá",
      "Ipupiara",
      "Irecê",
      "Itaguaçu da Bahia",
      "João Dourado",
      "Jussara",
      "Lapão",
      "Mulungu do Morro",
      "Presidente Dutra",
      "São Gabriel",
      "Uibaí",
      "Xique-Xique",
    ],
  },
  {
    territorio: "Itaparica",
    municipios: [
      "Abaré",
      "Chorrochó",
      "Glória",
      "Macururé",
      "Paulo Afonso",
      "Rodelas",
    ],
  },
  {
    territorio: "Litoral Norte e Agreste Baiano",
    municipios: [
      "Acajutiba",
      "Alagoinhas",
      "Aporá",
      "Araçás",
      "Aramari",
      "Cardeal da Silva",
      "Catu",
      "Conde",
      "Crisópolis",
      "Entre Rios",
      "Esplanada",
      "Inhambupe",
      "Itanagra",
      "Itapicuru",
      "Jandaíra",
      "Olindina",
      "Ouriçangas",
      "Pedrão",
      "Rio Real",
      "Sátiro Dias",
    ],
  },
  {
    territorio: "Médio Sudoeste da Bahia",
    municipios: [
      "Caatiba",
      "Firmino Alves",
      "Ibicuí",
      "Iguaí",
      "Itambé",
      "Itapetinga",
      "Itarantim",
      "Itororó",
      "Macarani",
      "Maiquinique",
      "Nova Canaã",
      "Potiraguá",
      "Santa Cruz da Vitória",
    ],
  },
  {
    territorio: "Litoral Sul",
    municipios: [
      "Almadina",
      "Arataca",
      "Aurelino Leal",
      "Barro Preto",
      "Buerarema",
      "Camacan",
      "Canavieiras",
      "Coaraci",
      "Floresta Azul",
      "Ibicaraí",
      "Ilhéus",
      "Itabuna",
      "Itacaré",
      "Itaju do Colônia",
      "Itajuípe",
      "Itapé",
      "Itapitanga",
      "Jussari",
      "Maraú",
      "Mascote",
      "Pau Brasil",
      "Santa Luzia",
      "São José da Vitória",
      "Ubaitaba",
      "Una",
      "Uruçuca",
    ],
  },
  {
    territorio: "Médio Rio de Contas",
    municipios: [
      "Aiquara",
      "Apuarema",
      "Barra do Rocha",
      "Boa Nova",
      "Dário Meira",
      "Gongogi",
      "Ibirataia",
      "Ipiaú",
      "Itagi",
      "Itagibá",
      "Itamari",
      "Jequié",
      "Jitaúna",
      "Manoel Vitorino",
      "Nova Ibiá",
      "Ubatã",
    ],
  },
  {
    territorio: "Metropolitano de Salvador",
    municipios: [
      "Camaçari",
      "Candeias",
      "Dias d'Ávila",
      "Itaparica",
      "Lauro de Freitas",
      "Madre de Deus",
      "Mata de São João",
      "Pojuca",
      "Salvador",
      "São Francisco do Conde",
      "São Sebastião do Passé",
      "Simões Filho",
      "Vera Cruz",
    ],
  },
  {
    territorio: "Piemonte da Diamantina",
    municipios: [
      "Caém",
      "Jacobina",
      "Miguel Calmon",
      "Mirangaba",
      "Ourolândia",
      "Saúde",
      "Serrolândia",
      "Umburanas",
      "Várzea Nova",
    ],
  },
  {
    territorio: "Piemonte do Paraguaçu",
    municipios: [
      "Boa Vista do Tupim",
      "Iaçu",
      "Ibiquera",
      "Itaberaba",
      "Itatim",
      "Lajedinho",
      "Macajuba",
      "Mundo Novo",
      "Piritiba",
      "Rafael Jambeiro",
      "Ruy Barbosa",
      "Santa Terezinha",
      "Tapiramutá",
    ],
  },
  {
    territorio: "Piemonte Norte do Itapicuru",
    municipios: [
      "Andorinha",
      "Antônio Gonçalves",
      "Caldeirão Grande",
      "Campo Formoso",
      "Filadélfia",
      "Jaguarari",
      "Pindobaçu",
      "Ponto Novo",
      "Senhor do Bonfim",
    ],
  },
  {
    territorio: "Portal do Sertão",
    municipios: [
      "Água Fria",
      "Amélia Rodrigues",
      "Anguera",
      "Antônio Cardoso",
      "Conceição da Feira",
      "Conceição do Jacuípe",
      "Coração de Maria",
      "Feira de Santana",
      "Ipecaetá",
      "Irará",
      "Santa Bárbara",
      "Santanópolis",
      "Santo Estêvão",
      "São Gonçalo dos Campos",
      "Tanquinho",
      "Teodoro Sampaio",
      "Terra Nova",
    ],
  },
  {
    territorio: "Recôncavo",
    municipios: [
      "Cabaceiras do Paraguaçu",
      "Cachoeira",
      "Castro Alves",
      "Conceição do Almeida",
      "Cruz das Almas",
      "Dom Macedo Costa",
      "Governador Mangabeira",
      "Maragogipe",
      "Muniz Ferreira",
      "Muritiba",
      "Nazaré",
      "Salinas da Margarida",
      "Santo Amaro",
      "Santo Antônio de Jesus",
      "São Félix",
      "São Felipe",
      "Sapeaçu",
      "Saubara",
      "Varzedo",
    ],
  },
  {
    territorio: "Semiárido Nordeste II",
    municipios: [
      "Adustina",
      "Antas",
      "Banzaê",
      "Cícero Dantas",
      "Cipó",
      "Coronel João Sá",
      "Euclides da Cunha",
      "Fátima",
      "Heliópolis",
      "Jeremoabo",
      "Nova Soure",
      "Novo Triunfo",
      "Paripiranga",
      "Pedro Alexandre",
      "Ribeira do Amparo",
      "Ribeira do Pombal",
      "Santa Brígida",
      "Sítio do Quinto",
    ],
  },
  {
    territorio: "Sertão do São Francisco",
    municipios: [
      "Campo Alegre de Lourdes",
      "Canudos",
      "Casa Nova",
      "Curaçá",
      "Juazeiro",
      "Pilão Arcado",
      "Remanso",
      "Sento Sé",
      "Sobradinho",
      "Uauá",
    ],
  },
  {
    territorio: "Sertão Produtivo",
    municipios: [
      "Brumado",
      "Caculé",
      "Caetité",
      "Candiba",
      "Contendas do Sincorá",
      "Dom Basílio",
      "Guanambi",
      "Ibiassucê",
      "Ituaçu",
      "Iuiu",
      "Lagoa Real",
      "Livramento de Nossa Senhora",
      "Malhada de Pedras",
      "Palmas de Monte Alto",
      "Pindaí",
      "Rio do Antônio",
      "Sebastião Laranjeiras",
      "Tanhaçu",
      "Tanque Novo",
      "Urandi",
    ],
  },
  {
    territorio: "Sisal",
    municipios: [
      "Araci",
      "Barrocas",
      "Biritinga",
      "Candeal",
      "Cansanção",
      "Conceição do Coité",
      "Ichu",
      "Itiúba",
      "Lamarão",
      "Monte Santo",
      "Nordestina",
      "Queimadas",
      "Quijingue",
      "Retirolândia",
      "Santaluz",
      "São Domingos",
      "Serrinha",
      "Teofilândia",
      "Tucano",
      "Valente",
    ],
  },
  {
    territorio: "Sudoeste Baiano (Vitória da Conquista)",
    municipios: [
      "Anagé",
      "Aracatu",
      "Barra do Choça",
      "Belo Campo",
      "Bom Jesus da Serra",
      "Caetanos",
      "Cândido Sales",
      "Caraíbas",
      "Condeúba",
      "Cordeiros",
      "Encruzilhada",
      "Guajeru",
      "Jacaraci",
      "Licínio de Almeida",
      "Maetinga",
      "Mirante",
      "Mortugaba",
      "Piripá",
      "Planalto",
      "Poções",
      "Presidente Jânio Quadros",
      "Ribeirão do Largo",
      "Tremedal",
      "Vitória da Conquista",
    ],
  },
  {
    territorio: "Vale do Jiquiriçá",
    municipios: [
      "Amargosa",
      "Brejões",
      "Cravolândia",
      "Elísio Medrado",
      "Irajuba",
      "Itaquara",
      "Itiruçu",
      "Jaguaquara",
      "Jiquiriçá",
      "Lafaiete Coutinho",
      "Laje",
      "Lajedo do Tabocal",
      "Maracás",
      "Milagres",
      "Mutuípe",
      "Nova Itarana",
      "Planaltino",
      "Santa Inês",
      "São Miguel das Matas",
      "Ubaíra",
    ],
  },
  {
    territorio: "Velho Chico",
    municipios: [
      "Barra",
      "Bom Jesus da Lapa",
      "Brotas de Macaúbas",
      "Carinhanha",
      "Feira da Mata",
      "Ibotirama",
      "Igaporã",
      "Malhada",
      "Matina",
      "Morpará",
      "Muquém do São Francisco",
      "Oliveira dos Brejinhos",
      "Paratinga",
      "Riacho de Santana",
      "Serra do Ramalho",
      "Sítio do Mato",
    ],
  },
];

const municSeed = async (prisma) => {
  const { data: municipios } = await axios.get(
    `https://servicodados.ibge.gov.br/api/v1/localidades/estados/ba/municipios`
  );

  const munic = municipios.map(({ id, nome }) => {
    const { territorio } = listaTerritoriosIdentidade.find(
      ({ territorio, municipios }) => {
        return municipios.includes(nome);
      }
    );
    return { idIBGE: id, nome, territorio };
  });

  try {
    return prisma.$transaction(async (prisma) => {
      await prisma.ba_TerritoriosIdentidade.deleteMany();
      await prisma.ba_Municipios.deleteMany();
      await prisma.ba_TerritoriosIdentidade.createMany({
        data: listaTerritoriosIdentidade.map(({ territorio }) => ({
          nome: territorio,
        })),
      });
      const territoriosFromBd =
        await prisma.ba_TerritoriosIdentidade.findMany();

      return prisma.ba_Municipios.createMany({
        data: munic.map(({ territorio, ...rest }) => ({
          ...rest,
          territorioIdentidade_Id: territoriosFromBd.find(
            ({ nome }) => nome === territorio
          ).id,
        })),
      });
    });
  } catch (error) {
    throw new Error(error);
  }
};

module.exports = { municSeed };
